# config.yml
paths:
  data:
    raw_data: "data/train.csv"
    clean_data: "data/clean_data.csv"

  models: 
    model_path: "models/best_model.pkl"

params:
  target: 'Attrition'
  test_size: 0.2
  random_state: 42
  class_weight_rfc: "balanced_subsample"
  recall: "recall"
  n_estimators: [100,200,500]
  max_depth: [5,10,null]
  min_samples_leaf: [1,5,10]
